name: rclean::get_libs()
on: pull_request
jobs:
  linux:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
    runs-on: ubuntu-latest
    container: rocker/tidyverse@sha256:d1d32475713ab198e4d98401d7670540076ab3e600eb9f702502ecc9cb56d32b
    steps:
    - uses: actions/checkout@v2
    - name: Install ropensci/Rclean
      run: |
        Rscript -e "install.packages('devtools', repos = 'https://cloud.r-project.org'); devtools::install_github('ropensci/Rclean')"
      shell:
        bash
    - name: Running Rclean::
      run: |
        Rscript -e "scripts <- list.files(".", pattern = ".R|.Rmd|.ipynb", recursive = TRUE); cat(unique(unlist(lapply(scripts, Rclean::get_libs))), sep = '\n')"
      shell:
        bash