# From here: https://github.com/reviewdog/action-misspell
name: reviewdog misspell
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: cgpu/action-misspell@v2
        with:
          github_token: ${{ secrets.github_token }}
          locale: "UK"
          reporter: github-pr-review # Available:  github-pr-review adds comments in PR conversation
          level: error